export interface HistoriaI {
  anulado?: number;
  ap_apellido1?: string;
  ap_apellido2?: string;
  ap_nombre1?: string;
  ap_nombre2?: string;
  barrio_nombre?: string;
  cama?: string | null;
  contador?: number;
  direccion_archivo?: null | string;
  direccion?: string;
  empresa_nombre?: string;
  especialidad_historia?: number;
  estado_folio?: number;
  etiqueta?: number;
  fecha_dig?: Date;
  fecha_nac?: Date;
  identificacion?: string;
  md_apellido1?: string;
  md_apellido2?: string;
  md_codigo?: number;
  md_especialidad?: number;
  md_identificacion?: string;
  md_nombre1?: string;
  md_nombre2?: string;
  md_reg_medico?: string;
  migra?: number;
  municipio?: number;
  no_factura?: number;
  no_historia?: string;
  nombre_estudio?: string;
  num_orden?: number;
  num_paciente_hist?: number;
  ordenar?: number;
  pabellon?: number;
  parametros?: string;
  sexo?: string;
  telefono?: string;
  texto01?: string;
  texto02?: string;
  texto03?: string;
  tipo_atencion?: number;
  usuario?: string;
  firma_med?: string;
}
